# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: EDOT
description: >-
  Elastic Distributions of OpenTelemetry is an open-source ecosystem of tailored OpenTelemetry distributions,
  comprising an OpenTelemetry Collector and various OpenTelemetry Language SDKs.
  Each EDOT distribution is asssembled with carefully curated OpenTelemetry components,
  then rigorously tested to ensure production readiness. 
  This provides a reliable and optimized OpenTelemetry experience with Elastic,
  enabling seamless adoption with confidence and expert support.
baseurl: "/opentelemetry" # the subpath of your site, e.g. /blog
url: "https://elastic.github.io/opentelemetry/" # the base hostname & protocol for your site, e.g. http://example.com
logo: /images/edot.png
favicon_ico: "/images/favicon.ico"

# Build settings
theme: just-the-docs

color_scheme: elastic

collections:
  edot-collector:
    output: true
  edot-sdks:
    output: true

callouts:
  note:
    title: "Note"
    color: el_green
  warning:
    title: "Warning"
    color: yellow

just_the_docs:
  collections:
    edot-collector:
      name: EDOT Collector
      nav_fold: true
    edot-sdks:
      name: EDOT SDKs
      nav_fold: true
  nav_sort: case_insensitive



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
